services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

jobs:
  include:
    - stage: coditsu
      before_script:
        - git checkout master
        - git reset --hard origin/master
        - git checkout -
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: docker run --volumes-from sources --network="host" coditsu/build-runner:latest

    - stage: specs
      language: ruby
      before_install:
        - gem install bundler
        - gem update --system
      script: bundle exec rspec
