services:
  - docker

dist: trusty
sudo: false
language: ruby
cache: bundler

git:
  depth: false

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

before_install:
  - gem install bundler
  - gem update --system
  - docker create -v /sources --name sources alpine:3.4 /bin/true
  - docker cp ./ sources:/sources
  - docker run --volumes-from sources --network="host" coditsu/build-runner:latest

script: bundle exec rspec
