services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

jobs:
  include:
    - stage: coditsu
      before_script:
        - git checkout master
        - git reset --hard origin/master
        - git checkout -
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: docker run --volumes-from sources --network="host" coditsu/build-runner:latest
