services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8

jobs:
  include:
    - stage: coditsu
      before_script:
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: >
        docker run
        -e CODITSU_API_KEY
        -e CODITSU_API_SECRET
        -e CODITSU_REPOSITORY_ID
        --volumes-from sources
        coditsu/build-runner:latest

    - stage: test
      language: ruby
      script: bundle exec rspec
      before_install:
        - gem install bundler
        - gem update --system

stages:
  - coditsu
  - test
