language: ruby

services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

jobs:
  include:
    - stage: coditsu
      before_script:
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: >
        docker run
        -e CODITSU_API_KEY
        -e CODITSU_API_SECRET
        -e CODITSU_REPOSITORY_ID
        --volumes-from sources
        coditsu/build-runner:latest

    - stage: test
      matrix:
        include:
          - rvm: 2.6.0
          - rvm: 2.5.3

      before_install:
        - gem install bundler
        - gem update --system
      script: bundle exec rspec

stages:
  - coditsu
  - test
